version: '2'
services:

  mysql:
    image: mysql:5.6
    container_name: nebula-db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      REDIS: redis
    volumes:
      - .:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: pass
    external_links:
      - mysql:db
    restart: always
    ports:
      - 8080:80

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]

  api:
    build:
      context: ./nebula-api
      dockerfile: Dockerfile
    volumes:
      - ./nebula-api:/app
      - /app/node_modules
    depends_on:
      - mysql
      - redis
    ports:
      - "3000:3000"
    command: yarn dev
    environment:
      NEW_REVIEW_TOPIC: new-review-topic
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: pass
      DB_DATABASE: adventureworks

  review-worker:
    build:
      context: ./nebula-review-worker
      dockerfile: Dockerfile
    volumes:
      - ./nebula-review-worker:/app
      - /app/node_modules
    depends_on:
      - redis
    command: yarn dev
    environment:
      NEW_REVIEW_TOPIC: new-review-topic
      REVIEW_APPROVED_TOPIC: review-approved-topic

